### ISSUE TITLE
Support prefix names with a hyphen

### ISSUE THREAD

**Issue by AlexanderWillner** [cygri/prefix.cc#18]
Steps that will reproduce the problem?
1. Open http://prefix.cc/omn-federation

What is the expected result?
To see the result that is shown at http://prefix.cc/omnfed

What happens instead?
Message: "bad prefix name “omn-federation"

Possible workaround:
Not using a hyphen.

Any additional information:
We've a number of ontologies such as http://lov.okfn.org/dataset/lov/vocabs/omnfed or http://lov.okfn.org/dataset/lov/vocabs/omnlc and a hyphens seems to be reasonable and not against any standard.

**Comment by AlexanderWillner** [comment]
Update: the given (correct) example shown another issue (prefix too long). This one would be a valid example: http://prefix.cc/omn-fed

**Comment by cygri** [comment]
@AlexanderWillner, as it says on that screen: “prefix.cc supports only a-z and 0-9 in prefixes.”

Prefix.cc is intended as a place to quickly look up commonly used prefixes. This only works if the prefixes are mnemonic. By not allowing hyphens, a situation is avoided where users have to remember whether `omnfed` or `omn-fed` or `o-mn-fed` was the right prefix. For the same reason, uppercase letters and overly long prefixes are not supported.

This has been a conscious decision and I am not inclined to change it. `WONTFIX`
