### ISSUE TITLE
Enable https

### ISSUE THREAD

**Issue by cygri** [cygri/prefix.cc#20]
Some browsers (at least Chrome) show a warning to the user when including http:// content in a https:// page. This affects pages that use prefix.cc via its APIs. Prefix.cc resolves via https://, but the certificate is invalid.

**Comment by danmichaelo** [comment]
:+1:

**Comment by LaurensRietveld** [comment]
I'd recommend using letsencrypt. Free ssl certificates that support automated renewal

**Comment by cygri** [comment]
Done, the site is now accessible at http://prefix.cc/ and https://prefix.cc/
