### ISSUE TITLE
Backwards Search

### ISSUE THREAD

**Issue by iddan** [cygri/prefix.cc#25]
For some ontologies, the suggested prefix is deep inside the document. I would like to be able to search by the ontology URI to see what is the most common prefix for it.

**Comment by cygri** [comment]
You can search by namespace, by copy-pasting the namespace URI into the search box.

Some ontologies are accessible under various URLs. Only the namespace URI will work.

**Comment by iddan** [comment]
I tried searching `http://www.w3.org/ns/ma-ont#` and it gave me no results.
Thanks for the fast reply!

**Comment by cygri** [comment]
I just tried that and it returns the prefix `ma`.

**Comment by iddan** [comment]
Oh, I missed that because I was expecting the layout to be reversed. Foolish me
