### ISSUE TITLE
Allow namespace URIs that end with underscore 

### ISSUE THREAD

**Issue by cygri** [cygri/prefix.cc#27]
Example: `http://purl.obolibrary.org/obo/GO_`

Currently, `/ # : =` are allowed. Add `_` to that list.

Requiring a special character at the end of the IRI at all is sensible because it prevents registering namespaces where the final special character is accidentally missing, like a missing required `#`. But I don't see a benefit in keeping the list of allowed terminal characters particularly narrow. So, adding `_` to the allowed terminals seems fine to me.

**Comment by cygri** [comment]
Done.

**Comment by cmungall** [comment]
This is great for OBO ontologies like GO, which have URIs like http://purl.obolibrary.org/obo/GO_0008150, which is shortened to `GO:0008150`
