### ISSUE TITLE
"Tools" section for the prefix.cc website 

### ISSUE THREAD

**Issue by sumutcan** [cygri/prefix.cc#30]
Hi, 
I use prefix.cc a lot and made a very simple plugin for Visual Studio Code for retrieving a namespace for a prefix (especially useful for Turtle and SPARQL).
Here is the link: https://marketplace.visualstudio.com/items?itemName=umutsims.prefix-cc 

I did not find any licensing information regarding the API, so I hope I am not violating anything.

Would you consider a section about tools that make use of (or help using) prefix.cc? Maybe there are other people  who developed some tools around prefix.cc.   

Greetings
Umut

**Comment by cygri** [comment]
Done: http://prefix.cc/about/users

https://github.com/cygri/prefix.cc/commit/cbc85c00e59e00cf4fee697374109fdd9027231a
