### ISSUE TITLE
Links generated to LOV pages from a prefix

### ISSUE THREAD

**Issue by gatemezing** [cygri/prefix.cc#32]
Currently, almost all the pages generated by prefix.cc to LOV are 404. 
This is maybe due to the changes in LOV some years ago. 
I suggest (if possible) to make the following changes in the code of the file `lib/site.class.php`, (If I understood well). 
This might give new pages to LOV. 
My suggestion would be to change the line 
`$links["http://lov.okfn.org/dataset/lov/details/vocabulary_$prefix.html"] = 'lov';`
by this one 
`$links["https://lov.linkeddata.es/dataset/lov/vocabs/$prefix"] = 'lov';`.

Thanks for this useful and incredible tool!

**Comment by cygri** [comment]
Done in #d51e0a9. Thank you!
