### ISSUE TITLE
SSL certificate is no longer valid

### ISSUE THREAD

**Issue by smessie** [cygri/prefix.cc#37]
The SSL certificate for https://prefix.cc is no longer valid.

Could this get an update?

**Comment by pmaria** [comment]
Just ran into this as well. Any chance this will be updated soon? Thanks in advance.

**Comment by jakubklimek** [comment]
I sent @cygri an email on September 6th with no answer/action. Unfortunately, this is preventing all Yasgui instances from autocompleting prefixes.

**Comment by smessie** [comment]
I've also sent him an email on June 22nd with no response.
I've created a small proxy at https://github.com/smessie/prefixcc-proxy if it would help anyone.
When set up with an SSL certificate, it forwards all requests to prefix.cc, so there is no need to host the entire prefix.cc database ourselves.
It uses the environment variable `HOSTNAME` to let you specify the hostname of your instance, used to replace `http://prefix.cc/` in the body of the responses so e.g. internal redirects and images in the HTML interface are also correctly proxied.

It's a workaround, not a proper fix though.

**Comment by cygri** [comment]
This should be sorted now.
